# Generated by Django 4.2.4 on 2023-08-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_categories_options_alter_projects_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='describtion',
            new_name='description',
        ),
    ]
