# Generated by Django 4.2.4 on 2023-08-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_describtion_projects_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Link',
            new_name='link',
        ),
    ]
