# Generated by Django 4.2.4 on 2023-08-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opinion',
            new_name='Opinions',
        ),
        migrations.AlterModelOptions(
            name='opinions',
            options={'verbose_name_plural': 'Opinions'},
        ),
    ]
