# Generated by Django 4.2.4 on 2023-08-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name_plural': 'Emails'},
        ),
    ]
