# Generated by Django 4.2.4 on 2023-08-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='describtion',
            new_name='description',
        ),
    ]
